default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: health
  host: localhost
  username: kapiobhee
  password: container

test:
  <<: *default
  database: db/test.postgresql

production:
  adapter: postgresql
  encoding: unicode
